// [config]
// expect_result: pass
// glsl_version: 4.30
// require_extensions: GL_ARB_compute_shader
// [end config]
//
// Compiler test for function inlining with image argument
// https://gitlab.freedesktop.org/mesa/mesa/-/issues/11980
//
#version 430 core
layout(local_size_x = 1) in;

writeonly uniform image3D img1;

void writeImage(writeonly image3D img1) {
	imageStore(img1, ivec3(1), vec4(1.0));
}

void main() {
	writeImage(img1);
}
